"""empty message

Revision ID: ffc708fbb55b
Revises: f2adbe1abefd
Create Date: 2020-07-23 14:01:47.424989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ffc708fbb55b'
down_revision = 'f2adbe1abefd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ammount', sa.Integer(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('payment_mode', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ammount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('payment_mode', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], name='order_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='order_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('my_order')
    # ### end Alembic commands ###
